org: gustavomorinaga
service: foodiary-api

plugins:
  - serverless-offline

custom: ${file(./sls/custom.yaml)}

provider: ${file(./sls/provider.yaml)}

package:
  individually: true

build: ${file(./sls/build.yaml)}

functions:
  - ${file(./sls/functions/auth.yaml)}
  - ${file(./sls/functions/meals.yaml)}
  - ${file(./sls/functions/events/s3/upload.yaml)}
  - ${file(./sls/functions/events/sqs/meal.yaml)}

resources:
  - ${file(./sls/resources/s3/uploads.yaml)}
  - ${file(./sls/resources/sqs/meals.yaml)}
